FROM node:20-alpine

# Install curl for healthcheck
RUN apk add --no-cache curl

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

EXPOSE 3002

# Run the background worker
CMD [ "npx", "ts-node", "src/workers/backgroundWorker.ts" ]
