FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

EXPOSE 3001

# Run TypeScript directly with ts-node in development
CMD [ "npm", "run", "dev" ]
